# Generated by Django 4.2.5 on 2023-10-06 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tempblog', '0002_personalblog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalblog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalblog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalblog',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
