# Generated by Django 4.2.5 on 2023-10-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempblog', '0003_personalblog_created_at_alter_personalblog_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalblog',
            name='image_title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
