# Generated by Django 4.2.5 on 2023-10-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempblog', '0004_personalblog_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalblog',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
